spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/ylbdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: ylb777
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.ylb.demo.spring.boot.mybits.entity
  mapper-locations: classpath:mapper/*.xml